/**
 * ____________________________________________________________________________
 *
 *           Project: BMW.live
 *           Version: 2.17.0-SNAPSHOT
 * ____________________________________________________________________________
 *
 *         $Revision:  $
 *    $LastChangedBy:  $
 *  $LastChangedDate:  $
 *       Description: see Javadoc
 * ____________________________________________________________________________
 *
 *         Copyright: (c) BMW AG 2011, all rights reserved
 * ____________________________________________________________________________
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.20 at 12:10:32 PM CEST 
//


package com.bmw.cdp.propertiesimporter.datatransform;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="page" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="resource" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="image">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="alt" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="p" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="section1">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="dualColumn">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="section1" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="p" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="section2" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="p" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="link">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="img_src" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="img_label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="highlight" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="section" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="p" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;element name="link" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="info" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="target" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="img_src" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="img_label" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                           &lt;attribute name="mode" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="teasers">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="teaser" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="img">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="link">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                                       &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "page",
    "resource",
    "image",
    "title",
    "heading",
    "p",
    "section1",
    "dualColumn",
    "highlight",
    "section",
    "teasers"
})
@XmlRootElement(name = "content")
public class Content {

    @XmlElement(required = true)
    protected String page;
    @XmlElement(required = true)
    protected String resource;
    @XmlElement(required = true)
    protected Content.Image image;
    @XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected String heading;
    @XmlElement(required = true)
    protected String p;
    @XmlElement(required = true)
    protected Content.Section1 section1;
    @XmlElement(required = true)
    protected Content.DualColumn dualColumn;
    @XmlElement(required = true)
    protected String highlight;
    protected List<Content.Section> section;
    @XmlElement(required = true)
    protected Content.Teasers teasers;

    /**
     * Gets the value of the page property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPage() {
        return page;
    }

    /**
     * Sets the value of the page property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPage(String value) {
        this.page = value;
    }

    /**
     * Gets the value of the resource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getResource() {
        return resource;
    }

    /**
     * Sets the value of the resource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setResource(String value) {
        this.resource = value;
    }

    /**
     * Gets the value of the image property.
     * 
     * @return
     *     possible object is
     *     {@link Content.Image }
     *     
     */
    public Content.Image getImage() {
        return image;
    }

    /**
     * Sets the value of the image property.
     * 
     * @param value
     *     allowed object is
     *     {@link Content.Image }
     *     
     */
    public void setImage(Content.Image value) {
        this.image = value;
    }

    /**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the heading property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHeading() {
        return heading;
    }

    /**
     * Sets the value of the heading property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHeading(String value) {
        this.heading = value;
    }

    /**
     * Gets the value of the p property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getP() {
        return p;
    }

    /**
     * Sets the value of the p property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setP(String value) {
        this.p = value;
    }

    /**
     * Gets the value of the section1 property.
     * 
     * @return
     *     possible object is
     *     {@link Content.Section1 }
     *     
     */
    public Content.Section1 getSection1() {
        return section1;
    }

    /**
     * Sets the value of the section1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link Content.Section1 }
     *     
     */
    public void setSection1(Content.Section1 value) {
        this.section1 = value;
    }

    /**
     * Gets the value of the dualColumn property.
     * 
     * @return
     *     possible object is
     *     {@link Content.DualColumn }
     *     
     */
    public Content.DualColumn getDualColumn() {
        return dualColumn;
    }

    /**
     * Sets the value of the dualColumn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Content.DualColumn }
     *     
     */
    public void setDualColumn(Content.DualColumn value) {
        this.dualColumn = value;
    }

    /**
     * Gets the value of the highlight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHighlight() {
        return highlight;
    }

    /**
     * Sets the value of the highlight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHighlight(String value) {
        this.highlight = value;
    }

    /**
     * Gets the value of the section property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the section property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Content.Section }
     * 
     * 
     */
    public List<Content.Section> getSection() {
        if (section == null) {
            section = new ArrayList<Content.Section>();
        }
        return this.section;
    }

    /**
     * Gets the value of the teasers property.
     * 
     * @return
     *     possible object is
     *     {@link Content.Teasers }
     *     
     */
    public Content.Teasers getTeasers() {
        return teasers;
    }

    /**
     * Sets the value of the teasers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Content.Teasers }
     *     
     */
    public void setTeasers(Content.Teasers value) {
        this.teasers = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="p" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="section1" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="p" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="section2" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="p" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="link">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="img_src" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="img_label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "title",
        "heading",
        "p",
        "section1",
        "section2",
        "link"
    })
    public static class DualColumn {

        @XmlElement(required = true)
        protected String title;
        @XmlElement(required = true)
        protected String heading;
        @XmlElement(required = true)
        protected String p;
        protected List<Content.DualColumn.Section1> section1;
        protected List<Content.DualColumn.Section2> section2;
        @XmlElement(required = true)
        protected Content.DualColumn.Link link;

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

        /**
         * Gets the value of the heading property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHeading() {
            return heading;
        }

        /**
         * Sets the value of the heading property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHeading(String value) {
            this.heading = value;
        }

        /**
         * Gets the value of the p property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP() {
            return p;
        }

        /**
         * Sets the value of the p property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP(String value) {
            this.p = value;
        }

        /**
         * Gets the value of the section1 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the section1 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSection1().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Content.DualColumn.Section1 }
         * 
         * 
         */
        public List<Content.DualColumn.Section1> getSection1() {
            if (section1 == null) {
                section1 = new ArrayList<Content.DualColumn.Section1>();
            }
            return this.section1;
        }

        /**
         * Gets the value of the section2 property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the section2 property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getSection2().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Content.DualColumn.Section2 }
         * 
         * 
         */
        public List<Content.DualColumn.Section2> getSection2() {
            if (section2 == null) {
                section2 = new ArrayList<Content.DualColumn.Section2>();
            }
            return this.section2;
        }

        /**
         * Gets the value of the link property.
         * 
         * @return
         *     possible object is
         *     {@link Content.DualColumn.Link }
         *     
         */
        public Content.DualColumn.Link getLink() {
            return link;
        }

        /**
         * Sets the value of the link property.
         * 
         * @param value
         *     allowed object is
         *     {@link Content.DualColumn.Link }
         *     
         */
        public void setLink(Content.DualColumn.Link value) {
            this.link = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="img_src" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="img_label" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="value" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "href",
            "label",
            "imgSrc",
            "imgLabel",
            "value"
        })
        public static class Link {

            @XmlElement(required = true)
            protected String href;
            @XmlElement(required = true)
            protected String label;
            @XmlElement(name = "img_src", required = true)
            protected String imgSrc;
            @XmlElement(name = "img_label", required = true)
            protected String imgLabel;
            @XmlElement(required = true)
            protected String value;

            /**
             * Gets the value of the href property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHref(String value) {
                this.href = value;
            }

            /**
             * Gets the value of the label property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLabel() {
                return label;
            }

            /**
             * Sets the value of the label property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLabel(String value) {
                this.label = value;
            }

            /**
             * Gets the value of the imgSrc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImgSrc() {
                return imgSrc;
            }

            /**
             * Sets the value of the imgSrc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImgSrc(String value) {
                this.imgSrc = value;
            }

            /**
             * Gets the value of the imgLabel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImgLabel() {
                return imgLabel;
            }

            /**
             * Sets the value of the imgLabel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImgLabel(String value) {
                this.imgLabel = value;
            }

            /**
             * Gets the value of the value property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getValue() {
                return value;
            }

            /**
             * Sets the value of the value property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setValue(String value) {
                this.value = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="p" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "heading",
            "p"
        })
        public static class Section1 {

            protected String heading;
            @XmlElement(required = true)
            protected String p;

            /**
             * Gets the value of the heading property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHeading() {
                return heading;
            }

            /**
             * Sets the value of the heading property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHeading(String value) {
                this.heading = value;
            }

            /**
             * Gets the value of the p property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP() {
                return p;
            }

            /**
             * Sets the value of the p property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP(String value) {
                this.p = value;
            }

        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="p" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "heading",
            "p"
        })
        public static class Section2 {

            @XmlElement(required = true)
            protected String heading;
            @XmlElement(required = true)
            protected String p;

            /**
             * Gets the value of the heading property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHeading() {
                return heading;
            }

            /**
             * Sets the value of the heading property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHeading(String value) {
                this.heading = value;
            }

            /**
             * Gets the value of the p property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getP() {
                return p;
            }

            /**
             * Sets the value of the p property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setP(String value) {
                this.p = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="alt" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "src",
        "width",
        "height",
        "alt",
        "title"
    })
    public static class Image {

        @XmlElement(required = true)
        protected String src;
        @XmlElement(required = true)
        protected String width;
        @XmlElement(required = true)
        protected String height;
        @XmlElement(required = true)
        protected String alt;
        @XmlElement(required = true)
        protected String title;

        /**
         * Gets the value of the src property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSrc() {
            return src;
        }

        /**
         * Sets the value of the src property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSrc(String value) {
            this.src = value;
        }

        /**
         * Gets the value of the width property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWidth() {
            return width;
        }

        /**
         * Sets the value of the width property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWidth(String value) {
            this.width = value;
        }

        /**
         * Gets the value of the height property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHeight() {
            return height;
        }

        /**
         * Sets the value of the height property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHeight(String value) {
            this.height = value;
        }

        /**
         * Gets the value of the alt property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAlt() {
            return alt;
        }

        /**
         * Sets the value of the alt property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAlt(String value) {
            this.alt = value;
        }

        /**
         * Gets the value of the title property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTitle() {
            return title;
        }

        /**
         * Sets the value of the title property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTitle(String value) {
            this.title = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="p" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *         &lt;element name="link" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="info" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="target" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="img_src" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="img_label" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
     *                 &lt;attribute name="mode" type="{http://www.w3.org/2001/XMLSchema}string" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "heading",
        "p",
        "link",
        "text"
    })
    public static class Section {

        @XmlElement(required = true)
        protected String heading;
        protected List<String> p;
        protected Content.Section.Link link;
        protected List<String> text;

        /**
         * Gets the value of the heading property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHeading() {
            return heading;
        }

        /**
         * Sets the value of the heading property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHeading(String value) {
            this.heading = value;
        }

        /**
         * Gets the value of the p property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the p property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getP().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getP() {
            if (p == null) {
                p = new ArrayList<String>();
            }
            return this.p;
        }

        /**
         * Gets the value of the link property.
         * 
         * @return
         *     possible object is
         *     {@link Content.Section.Link }
         *     
         */
        public Content.Section.Link getLink() {
            return link;
        }

        /**
         * Sets the value of the link property.
         * 
         * @param value
         *     allowed object is
         *     {@link Content.Section.Link }
         *     
         */
        public void setLink(Content.Section.Link value) {
            this.link = value;
        }

        /**
         * Gets the value of the text property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the text property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getText().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link String }
         * 
         * 
         */
        public List<String> getText() {
            if (text == null) {
                text = new ArrayList<String>();
            }
            return this.text;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="label" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="info" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="target" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="img_src" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="img_label" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
         *       &lt;attribute name="mode" type="{http://www.w3.org/2001/XMLSchema}string" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "label",
            "info",
            "url",
            "href",
            "target",
            "imgSrc",
            "imgLabel"
        })
        public static class Link {

            @XmlElement(required = true)
            protected String label;
            @XmlElement(required = true)
            protected String info;
            @XmlElement(required = true)
            protected String url;
            @XmlElement(required = true)
            protected String href;
            @XmlElement(required = true)
            protected String target;
            @XmlElement(name = "img_src", required = true)
            protected String imgSrc;
            @XmlElement(name = "img_label", required = true)
            protected String imgLabel;
            @XmlAttribute(name = "id")
            protected String id;
            @XmlAttribute(name = "mode")
            protected String mode;

            /**
             * Gets the value of the label property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getLabel() {
                return label;
            }

            /**
             * Sets the value of the label property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setLabel(String value) {
                this.label = value;
            }

            /**
             * Gets the value of the info property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getInfo() {
                return info;
            }

            /**
             * Sets the value of the info property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setInfo(String value) {
                this.info = value;
            }

            /**
             * Gets the value of the url property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getUrl() {
                return url;
            }

            /**
             * Sets the value of the url property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setUrl(String value) {
                this.url = value;
            }

            /**
             * Gets the value of the href property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getHref() {
                return href;
            }

            /**
             * Sets the value of the href property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setHref(String value) {
                this.href = value;
            }

            /**
             * Gets the value of the target property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getTarget() {
                return target;
            }

            /**
             * Sets the value of the target property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setTarget(String value) {
                this.target = value;
            }

            /**
             * Gets the value of the imgSrc property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImgSrc() {
                return imgSrc;
            }

            /**
             * Sets the value of the imgSrc property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImgSrc(String value) {
                this.imgSrc = value;
            }

            /**
             * Gets the value of the imgLabel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getImgLabel() {
                return imgLabel;
            }

            /**
             * Sets the value of the imgLabel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setImgLabel(String value) {
                this.imgLabel = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setId(String value) {
                this.id = value;
            }

            /**
             * Gets the value of the mode property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMode() {
                return mode;
            }

            /**
             * Sets the value of the mode property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMode(String value) {
                this.mode = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="p" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "heading",
        "p"
    })
    public static class Section1 {

        @XmlElement(required = true)
        protected String heading;
        @XmlElement(required = true)
        protected String p;

        /**
         * Gets the value of the heading property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHeading() {
            return heading;
        }

        /**
         * Sets the value of the heading property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHeading(String value) {
            this.heading = value;
        }

        /**
         * Gets the value of the p property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getP() {
            return p;
        }

        /**
         * Sets the value of the p property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setP(String value) {
            this.p = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="heading" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="teaser" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="img">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="link">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *                             &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "heading",
        "teaser"
    })
    public static class Teasers {

        @XmlElement(required = true)
        protected String heading;
        protected List<Content.Teasers.Teaser> teaser;

        /**
         * Gets the value of the heading property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHeading() {
            return heading;
        }

        /**
         * Sets the value of the heading property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHeading(String value) {
            this.heading = value;
        }

        /**
         * Gets the value of the teaser property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the teaser property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTeaser().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Content.Teasers.Teaser }
         * 
         * 
         */
        public List<Content.Teasers.Teaser> getTeaser() {
            if (teaser == null) {
                teaser = new ArrayList<Content.Teasers.Teaser>();
            }
            return this.teaser;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="img">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="link">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
         *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "img",
            "link",
            "text"
        })
        public static class Teaser {

            @XmlElement(required = true)
            protected Content.Teasers.Teaser.Img img;
            @XmlElement(required = true)
            protected Content.Teasers.Teaser.Link link;
            @XmlElement(required = true)
            protected String text;

            /**
             * Gets the value of the img property.
             * 
             * @return
             *     possible object is
             *     {@link Content.Teasers.Teaser.Img }
             *     
             */
            public Content.Teasers.Teaser.Img getImg() {
                return img;
            }

            /**
             * Sets the value of the img property.
             * 
             * @param value
             *     allowed object is
             *     {@link Content.Teasers.Teaser.Img }
             *     
             */
            public void setImg(Content.Teasers.Teaser.Img value) {
                this.img = value;
            }

            /**
             * Gets the value of the link property.
             * 
             * @return
             *     possible object is
             *     {@link Content.Teasers.Teaser.Link }
             *     
             */
            public Content.Teasers.Teaser.Link getLink() {
                return link;
            }

            /**
             * Sets the value of the link property.
             * 
             * @param value
             *     allowed object is
             *     {@link Content.Teasers.Teaser.Link }
             *     
             */
            public void setLink(Content.Teasers.Teaser.Link value) {
                this.link = value;
            }

            /**
             * Gets the value of the text property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getText() {
                return text;
            }

            /**
             * Sets the value of the text property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setText(String value) {
                this.text = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="src" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="width" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="height" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "src",
                "width",
                "height"
            })
            public static class Img {

                @XmlElement(required = true)
                protected String src;
                @XmlElement(required = true)
                protected String width;
                @XmlElement(required = true)
                protected String height;

                /**
                 * Gets the value of the src property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getSrc() {
                    return src;
                }

                /**
                 * Sets the value of the src property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setSrc(String value) {
                    this.src = value;
                }

                /**
                 * Gets the value of the width property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getWidth() {
                    return width;
                }

                /**
                 * Sets the value of the width property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setWidth(String value) {
                    this.width = value;
                }

                /**
                 * Gets the value of the height property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHeight() {
                    return height;
                }

                /**
                 * Sets the value of the height property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHeight(String value) {
                    this.height = value;
                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="href" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
             *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "href",
                "text"
            })
            public static class Link {

                @XmlElement(required = true)
                @XmlSchemaType(name = "anyURI")
                protected String href;
                @XmlElement(required = true)
                protected String text;

                /**
                 * Gets the value of the href property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getHref() {
                    return href;
                }

                /**
                 * Sets the value of the href property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setHref(String value) {
                    this.href = value;
                }

                /**
                 * Gets the value of the text property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getText() {
                    return text;
                }

                /**
                 * Sets the value of the text property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setText(String value) {
                    this.text = value;
                }

            }

        }

    }

}
