/**
 * ____________________________________________________________________________
 *
 *           Project: BMW.live
 *           Version: 2.17.0-SNAPSHOT
 * ____________________________________________________________________________
 *
 *         $Revision:  $
 *    $LastChangedBy:  $
 *  $LastChangedDate:  $
 *       Description: see Javadoc
 * ____________________________________________________________________________
 *
 *         Copyright: (c) BMW AG 2011, all rights reserved
 * ____________________________________________________________________________
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.07.20 at 12:10:32 PM CEST 
//

package com.bmw.cdp.propertiesimporter.datatransform;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the
 * com.bmw.cdp.propertiesimporter.datatransform package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * com.bmw.cdp.propertiesimporter.datatransform
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link Content }
	 * 
	 */
	public Content createContent() {
		return new Content();
	}

	/**
	 * Create an instance of {@link Content.Teasers }
	 * 
	 */
	public Content.Teasers createContentTeasers() {
		return new Content.Teasers();
	}

	/**
	 * Create an instance of {@link Content.Teasers.Teaser }
	 * 
	 */
	public Content.Teasers.Teaser createContentTeasersTeaser() {
		return new Content.Teasers.Teaser();
	}

	/**
	 * Create an instance of {@link Content.Section }
	 * 
	 */
	public Content.Section createContentSection() {
		return new Content.Section();
	}

	/**
	 * Create an instance of {@link Content.DualColumn }
	 * 
	 */
	public Content.DualColumn createContentDualColumn() {
		return new Content.DualColumn();
	}

	/**
	 * Create an instance of {@link Content.Image }
	 * 
	 */
	public Content.Image createContentImage() {
		return new Content.Image();
	}

	/**
	 * Create an instance of {@link Content.Section1 }
	 * 
	 */
	public Content.Section1 createContentSection1() {
		return new Content.Section1();
	}

	/**
	 * Create an instance of {@link Content.Teasers.Teaser.Img }
	 * 
	 */
	public Content.Teasers.Teaser.Img createContentTeasersTeaserImg() {
		return new Content.Teasers.Teaser.Img();
	}

	/**
	 * Create an instance of {@link Content.Teasers.Teaser.Link }
	 * 
	 */
	public Content.Teasers.Teaser.Link createContentTeasersTeaserLink() {
		return new Content.Teasers.Teaser.Link();
	}

	/**
	 * Create an instance of {@link Content.Section.Link }
	 * 
	 */
	public Content.Section.Link createContentSectionLink() {
		return new Content.Section.Link();
	}

	/**
	 * Create an instance of {@link Content.DualColumn.Section1 }
	 * 
	 */
	public Content.DualColumn.Section1 createContentDualColumnSection1() {
		return new Content.DualColumn.Section1();
	}

	/**
	 * Create an instance of {@link Content.DualColumn.Section2 }
	 * 
	 */
	public Content.DualColumn.Section2 createContentDualColumnSection2() {
		return new Content.DualColumn.Section2();
	}

	/**
	 * Create an instance of {@link Content.DualColumn.Link }
	 * 
	 */
	public Content.DualColumn.Link createContentDualColumnLink() {
		return new Content.DualColumn.Link();
	}

}
