/**
 * ____________________________________________________________________________
 *
 *           Project: BMW.live
 *           Version: 2.24.0-SNAPSHOT
 * ____________________________________________________________________________
 *
 *         $Revision:  $
 *    $LastChangedBy:  $
 *  $LastChangedDate:  $
 *       Description: see Javadoc
 * ____________________________________________________________________________
 *
 *         Copyright: (c) BMW AG 2011, all rights reserved
 * ____________________________________________________________________________
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.21 at 10:12:15 AM CET 
//


package com.bmw.cdp.propertiesimporter.data;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}TEXTTYP"/>
 *         &lt;element ref="{}VERBAUUNGSORT"/>
 *         &lt;element ref="{}SGFAMILIE"/>
 *         &lt;element ref="{}FZG-PROJEKT"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "texttyp",
    "verbauungsort",
    "sgfamilie",
    "fzgprojekt"
})
@XmlRootElement(name = "GUELTIGKEIT")
public class GUELTIGKEIT {

    @XmlElement(name = "TEXTTYP", required = true)
    protected TEXTTYP texttyp;
    @XmlElement(name = "VERBAUUNGSORT", required = true)
    protected VERBAUUNGSORT verbauungsort;
    @XmlElement(name = "SGFAMILIE", required = true)
    protected SGFAMILIE sgfamilie;
    @XmlElement(name = "FZG-PROJEKT", required = true)
    protected FZGPROJEKT fzgprojekt;

    /**
     * Gets the value of the texttyp property.
     * 
     * @return
     *     possible object is
     *     {@link TEXTTYP }
     *     
     */
    public TEXTTYP getTEXTTYP() {
        return texttyp;
    }

    /**
     * Sets the value of the texttyp property.
     * 
     * @param value
     *     allowed object is
     *     {@link TEXTTYP }
     *     
     */
    public void setTEXTTYP(TEXTTYP value) {
        this.texttyp = value;
    }

    /**
     * Gets the value of the verbauungsort property.
     * 
     * @return
     *     possible object is
     *     {@link VERBAUUNGSORT }
     *     
     */
    public VERBAUUNGSORT getVERBAUUNGSORT() {
        return verbauungsort;
    }

    /**
     * Sets the value of the verbauungsort property.
     * 
     * @param value
     *     allowed object is
     *     {@link VERBAUUNGSORT }
     *     
     */
    public void setVERBAUUNGSORT(VERBAUUNGSORT value) {
        this.verbauungsort = value;
    }

    /**
     * Gets the value of the sgfamilie property.
     * 
     * @return
     *     possible object is
     *     {@link SGFAMILIE }
     *     
     */
    public SGFAMILIE getSGFAMILIE() {
        return sgfamilie;
    }

    /**
     * Sets the value of the sgfamilie property.
     * 
     * @param value
     *     allowed object is
     *     {@link SGFAMILIE }
     *     
     */
    public void setSGFAMILIE(SGFAMILIE value) {
        this.sgfamilie = value;
    }

    /**
     * Gets the value of the fzgprojekt property.
     * 
     * @return
     *     possible object is
     *     {@link FZGPROJEKT }
     *     
     */
    public FZGPROJEKT getFZGPROJEKT() {
        return fzgprojekt;
    }

    /**
     * Sets the value of the fzgprojekt property.
     * 
     * @param value
     *     allowed object is
     *     {@link FZGPROJEKT }
     *     
     */
    public void setFZGPROJEKT(FZGPROJEKT value) {
        this.fzgprojekt = value;
    }

}
