/**
 * ____________________________________________________________________________
 *
 *           Project: BMW.live
 *           Version: 2.24.0-SNAPSHOT
 * ____________________________________________________________________________
 *
 *         $Revision:  $
 *    $LastChangedBy:  $
 *  $LastChangedDate:  $
 *       Description: see Javadoc
 * ____________________________________________________________________________
 *
 *         Copyright: (c) BMW AG 2011, all rights reserved
 * ____________________________________________________________________________
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.21 at 10:12:15 AM CET 
//

package com.bmw.cdp.propertiesimporter.data;

import java.math.BigInteger;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.bmw.cdp.propertiesimporter.data
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _KOMMENTAR_QNAME = new QName("", "KOMMENTAR");
	private final static QName _ERZEUGER_QNAME = new QName("", "ERZEUGER");
	private final static QName _MONAT_QNAME = new QName("", "MONAT");
	private final static QName _ISTUFE_QNAME = new QName("", "I-STUFE");
	private final static QName _JAHR_QNAME = new QName("", "JAHR");
	private final static QName _ERZEUGUNGSDATUM_QNAME = new QName("", "ERZEUGUNGSDATUM");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package:
	 * com.bmw.cdp.propertiesimporter.data
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link BAUSTAND }
	 * 
	 */
	public BAUSTAND createBAUSTAND() {
		return new BAUSTAND();
	}

	/**
	 * Create an instance of {@link SPRACHVARIANTE }
	 * 
	 */
	public SPRACHVARIANTE createSPRACHVARIANTE() {
		return new SPRACHVARIANTE();
	}

	/**
	 * Create an instance of {@link TEXTE }
	 * 
	 */
	public TEXTE createTEXTE() {
		return new TEXTE();
	}

	/**
	 * Create an instance of {@link TEXT }
	 * 
	 */
	public TEXT createTEXT() {
		return new TEXT();
	}

	/**
	 * Create an instance of {@link FAHRZEUGTEXTE }
	 * 
	 */
	public FAHRZEUGTEXTE createFAHRZEUGTEXTE() {
		return new FAHRZEUGTEXTE();
	}

	/**
	 * Create an instance of {@link HEADER }
	 * 
	 */
	public HEADER createHEADER() {
		return new HEADER();
	}

	/**
	 * Create an instance of {@link GUELTIGKEIT }
	 * 
	 */
	public GUELTIGKEIT createGUELTIGKEIT() {
		return new GUELTIGKEIT();
	}

	/**
	 * Create an instance of {@link TEXTTYP }
	 * 
	 */
	public TEXTTYP createTEXTTYP() {
		return new TEXTTYP();
	}

	/**
	 * Create an instance of {@link VERBAUUNGSORT }
	 * 
	 */
	public VERBAUUNGSORT createVERBAUUNGSORT() {
		return new VERBAUUNGSORT();
	}

	/**
	 * Create an instance of {@link SGFAMILIE }
	 * 
	 */
	public SGFAMILIE createSGFAMILIE() {
		return new SGFAMILIE();
	}

	/**
	 * Create an instance of {@link FZGPROJEKT }
	 * 
	 */
	public FZGPROJEKT createFZGPROJEKT() {
		return new FZGPROJEKT();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "KOMMENTAR")
	public JAXBElement<String> createKOMMENTAR(String value) {
		return new JAXBElement<String>(_KOMMENTAR_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ERZEUGER")
	public JAXBElement<String> createERZEUGER(String value) {
		return new JAXBElement<String>(_ERZEUGER_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "MONAT")
	public JAXBElement<BigInteger> createMONAT(BigInteger value) {
		return new JAXBElement<BigInteger>(_MONAT_QNAME, BigInteger.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "I-STUFE")
	public JAXBElement<String> createISTUFE(String value) {
		return new JAXBElement<String>(_ISTUFE_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "JAHR")
	public JAXBElement<BigInteger> createJAHR(BigInteger value) {
		return new JAXBElement<BigInteger>(_JAHR_QNAME, BigInteger.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }
	 * {@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ERZEUGUNGSDATUM")
	public JAXBElement<BigInteger> createERZEUGUNGSDATUM(BigInteger value) {
		return new JAXBElement<BigInteger>(_ERZEUGUNGSDATUM_QNAME, BigInteger.class, null, value);
	}

}
