/**
 * ____________________________________________________________________________
 *
 *           Project: BMW.live
 *           Version: 2.24.0-SNAPSHOT
 * ____________________________________________________________________________
 *
 *         $Revision:  $
 *    $LastChangedBy:  $
 *  $LastChangedDate:  $
 *       Description: see Javadoc
 * ____________________________________________________________________________
 *
 *         Copyright: (c) BMW AG 2011, all rights reserved
 * ____________________________________________________________________________
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.21 at 10:12:15 AM CET 
//


package com.bmw.kpi.propertiesimporter.data;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}ERZEUGER"/>
 *         &lt;element ref="{}ERZEUGUNGSDATUM"/>
 *         &lt;element ref="{}GUELTIGKEIT"/>
 *         &lt;element ref="{}I-STUFE"/>
 *         &lt;element ref="{}BAUSTAND"/>
 *         &lt;element ref="{}KOMMENTAR"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "erzeuger",
    "erzeugungsdatum",
    "gueltigkeit",
    "istufe",
    "baustand",
    "kommentar"
})
@XmlRootElement(name = "HEADER")
public class HEADER {

    @XmlElement(name = "ERZEUGER", required = true)
    protected String erzeuger;
    @XmlElement(name = "ERZEUGUNGSDATUM", required = true)
    protected BigInteger erzeugungsdatum;
    @XmlElement(name = "GUELTIGKEIT", required = true)
    protected GUELTIGKEIT gueltigkeit;
    @XmlElement(name = "I-STUFE", required = true)
    protected String istufe;
    @XmlElement(name = "BAUSTAND", required = true)
    protected BAUSTAND baustand;
    @XmlElement(name = "KOMMENTAR", required = true)
    protected String kommentar;

    /**
     * Gets the value of the erzeuger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getERZEUGER() {
        return erzeuger;
    }

    /**
     * Sets the value of the erzeuger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setERZEUGER(String value) {
        this.erzeuger = value;
    }

    /**
     * Gets the value of the erzeugungsdatum property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getERZEUGUNGSDATUM() {
        return erzeugungsdatum;
    }

    /**
     * Sets the value of the erzeugungsdatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setERZEUGUNGSDATUM(BigInteger value) {
        this.erzeugungsdatum = value;
    }

    /**
     * Gets the value of the gueltigkeit property.
     * 
     * @return
     *     possible object is
     *     {@link GUELTIGKEIT }
     *     
     */
    public GUELTIGKEIT getGUELTIGKEIT() {
        return gueltigkeit;
    }

    /**
     * Sets the value of the gueltigkeit property.
     * 
     * @param value
     *     allowed object is
     *     {@link GUELTIGKEIT }
     *     
     */
    public void setGUELTIGKEIT(GUELTIGKEIT value) {
        this.gueltigkeit = value;
    }

    /**
     * Gets the value of the istufe property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getISTUFE() {
        return istufe;
    }

    /**
     * Sets the value of the istufe property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setISTUFE(String value) {
        this.istufe = value;
    }

    /**
     * Gets the value of the baustand property.
     * 
     * @return
     *     possible object is
     *     {@link BAUSTAND }
     *     
     */
    public BAUSTAND getBAUSTAND() {
        return baustand;
    }

    /**
     * Sets the value of the baustand property.
     * 
     * @param value
     *     allowed object is
     *     {@link BAUSTAND }
     *     
     */
    public void setBAUSTAND(BAUSTAND value) {
        this.baustand = value;
    }

    /**
     * Gets the value of the kommentar property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKOMMENTAR() {
        return kommentar;
    }

    /**
     * Sets the value of the kommentar property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKOMMENTAR(String value) {
        this.kommentar = value;
    }

}
