/**
 * ____________________________________________________________________________
 *
 *           Project: BMW.live
 *           Version: 2.24.0-SNAPSHOT
 * ____________________________________________________________________________
 *
 *         $Revision:  $
 *    $LastChangedBy:  $
 *  $LastChangedDate:  $
 *       Description: see Javadoc
 * ____________________________________________________________________________
 *
 *         Copyright: (c) BMW AG 2011, all rights reserved
 * ____________________________________________________________________________
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.21 at 10:12:15 AM CET 
//


package com.bmw.kpi.propertiesimporter.data;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}SPRACHVARIANTE" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="IDENTIFIER" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="NUMIDENTIFIER" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sprachvariante"
})
@XmlRootElement(name = "TEXT")
public class TEXT {

    @XmlElement(name = "SPRACHVARIANTE", required = true)
    protected List<SPRACHVARIANTE> sprachvariante;
    @XmlAttribute(name = "IDENTIFIER", required = true)
    protected String identifier;
    @XmlAttribute(name = "NUMIDENTIFIER", required = true)
    protected BigInteger numidentifier;

    /**
     * Gets the value of the sprachvariante property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sprachvariante property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSPRACHVARIANTE().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SPRACHVARIANTE }
     * 
     * 
     */
    public List<SPRACHVARIANTE> getSPRACHVARIANTE() {
        if (sprachvariante == null) {
            sprachvariante = new ArrayList<SPRACHVARIANTE>();
        }
        return this.sprachvariante;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDENTIFIER() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDENTIFIER(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the numidentifier property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getNUMIDENTIFIER() {
        return numidentifier;
    }

    /**
     * Sets the value of the numidentifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setNUMIDENTIFIER(BigInteger value) {
        this.numidentifier = value;
    }

}
